name: CI
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Deploy Web
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - run: ls

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
      - run: ls
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yagoazedias/dog-escaper-web:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}